### ISSUE TITLE
Entities: Map Entities To Database Tables

### ISSUE THREAD

**Issue by kshakirov** [pbs257/my_active#4]
1. Describe in written the entities we use (you can use any graphic tool which can show the relations among entities) and their relations.
2. Then map them to the tables, we talked about it in the recent meeting.
3. Then, try to write pseudo (or real) code (of migration) which corresponds to the above mentioned entities and their relations.

**Comment by kshakirov** [comment]
let us create folder -doc in root of the project and keep similar files there

**Comment by pbs257** [comment]
![my_active table relationships mapping](https://cloud.githubusercontent.com/assets/5029921/13042849/5ff2d624-d389-11e5-9b63-6518278e933e.png)
1. Entities: Orders, Customers, Products and Users. Orders relates to Customers via Customer_ID and Products via Product_ID. Each corresponding table relates to Orders via Orders_ID.
