### ISSUE TITLE
Ruby: Modules 

### ISSUE THREAD

**Issue by kshakirov** [pbs257/my_active#5]
Read about Modules, next time explain me in general what  modules in Ruby are,
make any example code of module and its use

**Comment by kshakirov** [comment]
Describe usage of modules as namespaces or packages, create an example of such a usage

**Comment by pbs257** [comment]
Two separate classes can have the same name and be referenced individually by means of a namespace. In other words, if at least one class is nested within a module, it can have the same name as another class outside of the module and be referenced with a double-colon constant lookup token after the module name and before the class name. 

Example:
module Oyster
  class Pearl
    def status
      puts "I'm inside of an oyster!"
    end
  end
class Pearl
  def status
    puts "I'm a part of a necklace!"
  end
end 

pearl_finder = Oyster::Pearl.new
pearl_finder.status

OUTPUT:
I'm inside of an oyster!
